// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMĐT.Models;

namespace TMĐT.Migrations
{
    [DbContext(typeof(PaymentDetailContext))]
    [Migration("20200509173234_changeModel")]
    partial class changeModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TMĐT.Models.PaymentDetail", b =>
                {
                    b.Property<int>("PM_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CARD_NUMBER")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("CARD_OWNER_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<string>("EXPIRATION_DATE")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.HasKey("PM_ID");

                    b.ToTable("PaymentDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
